import 'dart:collection';

import 'package:appflowy_editor/appflowy_editor.dart';
import 'package:collection/collection.dart';
import 'package:flutter/material.dart';
import 'package:fractional_indexing_dart/fractional_indexing_dart.dart';
import 'package:uuid/uuid.dart';

abstract class NodeExternalValues {
  const NodeExternalValues();
}

/// [Node] represents a node in the document tree.
///
/// It contains three parts:
///   - [type]: The type of the node to determine which block component to render it.
///   - [data]: The data of the node to determine how to render it.
///   - [children]: The children of the node.
///
///
/// Json format:
/// ```
/// {
///   'type': String,
///   'data': Map<String, Object>
///   'children': List<Node>,
/// }
/// ```
///
final class Node extends ChangeNotifier
    with LinkedListEntry<Node>, RankedLinkedListEntry<Node> {
  Node({
    required this.type,
    @Deprecated(
      'databaseIndex is carried through to JSON but never read inside the '
      'editor. Kept for downstream callers that still depend on the field '
      '(remove once those migrate). Prefer `rank` for ordering.',
    )
    this.databaseIndex = -1,
    String? id,
    String? initialRank,
    this.parent,
    this._attributes = const {},
    Iterable<Node> children = const [],
  }) : _children = RankedLinkedList<Node>()
         ..addAll(children.map((e) => e..unlink())),
       id = id ?? Uuid().v4() {
    if (initialRank != null) {
      super.rank = initialRank;
    }
    for (final child in children) {
      child.parent = this;
    }

    if (sectionParser != null && text != null) {
      sections = sectionParser!(this);
    }
  }

  static Sections? Function(Node node)? sectionParser;

  /// Parses a [Map] into a [Node]
  ///
  factory Node.fromJson(Map<String, dynamic> json) {
    final node = Node(
      id: json['id'] as String? ?? Uuid().v4(),
      initialRank: json['rank'] as String?,
      databaseIndex: json['databaseIndex'] != null
          ? (json['databaseIndex'] as num).toDouble()
          : -1,
      type: json['type'] as String,
      attributes: Attributes.from(json['data'] as Map? ?? {}),
      children: (json['children'] as List? ?? [])
          .map((e) => Map<String, Object>.from(e))
          .map((e) => Node.fromJson(e)),
    );

    for (final child in node.children) {
      child.parent = node;
    }

    return node;
  }

  String? get text {
    final textInserts = delta?.whereType<TextInsert>();
    final text = textInserts?.map((t) => t.text).join();

    if (text != null && text.isEmpty) {
      return null;
    }

    return text;
  }

  int? get sectionCount => sections?.length;

  Sections? sections;

  /// The type of the node.
  final String type;

  /// The id of the node.
  ///
  /// If not provided, it will be generated by [Uuid].
  /// In most cases, you don't need to modify it after the node is created.
  String id;

  /// Numeric position carried verbatim through `toJson` / `fromJson` for
  /// downstream callers that wire it into a backend's row index. The editor
  /// itself doesn't read this — node ordering is driven by [rank] (fractional
  /// indexing). New code shouldn't depend on this; treat it as
  /// opaque metadata.
  @Deprecated(
    'databaseIndex is carried through to JSON but never read inside the '
    'editor. Kept for downstream callers that still depend on the field '
    '(remove once those migrate). Prefer `rank` for ordering.',
  )
  final double databaseIndex;

  // @Deprecated('Use type instead')
  // String get id => type;

  /// The parent of the node.
  Node? parent;

  /// The children of the node.
  final RankedLinkedList<Node> _children;
  List<Node> get children {
    return _children.indexedList;
  }

  /// The attributes of the node.
  Attributes _attributes;

  /// Read-only view onto the node's attribute map.
  ///
  /// Previously this getter returned a fresh `{..._attributes}` copy on
  /// every call — there are ~150 read sites across the editor and several
  /// fire on every keystroke / selection update, so the copy was real
  /// per-frame overhead. `UnmodifiableMapView` (from `dart:collection`,
  /// already imported) is O(1) to construct and read-through; the only
  /// behavioral difference is that callers can't mutate the returned map
  /// directly. The fresh-copy version silently swallowed any such
  /// mutation anyway (writes went into the throwaway copy), so this is
  /// strictly safer for callers and faster for the editor.
  Attributes get attributes => UnmodifiableMapView(_attributes);

  /// The path of the node.
  ///
  /// Walking back up to the root is non-trivial — each level calls
  /// `parent.children.indexOf(this)`, which is O(siblings). For deeply
  /// nested blocks (tables, columns, lists) this getter is called many
  /// times per frame (selection paths, transaction.dart, builder
  /// contexts), so the computed path is memoized and invalidated
  /// whenever any tree mutation runs (via [_bumpPathGeneration]).
  Path get path {
    if (_cachedPath != null && _cachedPathGeneration == _globalPathGeneration) {
      return _cachedPath!;
    }
    final computed = _computePath();
    _cachedPath = computed;
    _cachedPathGeneration = _globalPathGeneration;
    return computed;
  }

  Path? _cachedPath;
  int _cachedPathGeneration = -1;

  // Bumped every time the tree shape changes anywhere in the process.
  // `path` cached on a Node is valid only while its `_cachedPathGeneration`
  // matches this counter. We use a single global counter rather than a
  // per-document one so any reachable Node can invalidate without needing
  // a back-reference to a Document.
  static int _globalPathGeneration = 0;
  static void _bumpPathGeneration() {
    _globalPathGeneration++;
  }

  NodeExternalValues? externalValues;

  /// this value is used to store temporary data,
  ///   and will be cleared after the node is rendered
  Map? extraInfos;

  // Render Part
  final key = GlobalKey();
  final layerLink = LayerLink();

  void notify() {
    notifyListeners();
  }

  /// Update the attributes of the node.
  ///
  void updateAttributes(Attributes attributes) {
    _attributes = composeAttributes(this.attributes, attributes) ?? {};

    notifyListeners();
  }

  /// Grabs the [Node] from this [Node]s children
  /// at a given index, if the index exists.
  ///
  Node? childAtIndexOrNull(int index) {
    if (children.length <= index || index < 0) {
      return null;
    }

    return children.elementAt(index);
  }

  Node? childAtPath(Path path) {
    if (path.isEmpty) {
      return this;
    }

    final index = path.first;
    final child = childAtIndexOrNull(index);

    return child?.childAtPath(path.sublist(1));
  }

  void insertAtRank(String rank, Node entry) {
    AppFlowyEditorLog.editor.debug('insert Node $entry at rank $rank');

    entry._resetRelationshipIfNeeded();
    entry.parent = this;

    _children.markAsDirty();
    _bumpPathGeneration();

    // if the rank is already exists, it will throw an error
    _children.insert(rank, entry);

    notifyListeners();
  }

  /// Inserts a [Node] at a given [index]
  ///
  /// If no [index] is supplied, inserts at the
  /// end of the [Node].
  ///
  void insert(Node entry, {int? index}) {
    final length = _children.length;
    index ??= length;

    AppFlowyEditorLog.editor.debug(
      'insert Node $entry at path ${path + [index]}}',
    );

    entry._resetRelationshipIfNeeded();
    entry.parent = this;

    _children.markAsDirty();
    _bumpPathGeneration();

    if (_children.isEmpty) {
      _children.add(entry);
      notifyListeners();

      return;
    }

    // If index is out of range, insert at the end.
    // If index is negative, insert at the beginning.
    // If index is positive, insert at the index.
    if (index >= length) {
      _children.last.insertAfter(entry);
    } else if (index <= 0) {
      _children.first.insertBefore(entry);
    } else {
      childAtIndexOrNull(index)?.insertBefore(entry);
    }
  }

  @override
  void insertAfter(Node entry) {
    entry._resetRelationshipIfNeeded();
    entry.parent = parent;
    super.insertAfter(entry);

    parent?._children.markAsDirty();
    _bumpPathGeneration();

    // Notifies the new node.
    parent?.notifyListeners();
  }

  @override
  void insertBefore(Node entry) {
    entry._resetRelationshipIfNeeded();
    entry.parent = parent;
    super.insertBefore(entry);

    parent?._children.markAsDirty();
    _bumpPathGeneration();

    // Notifies the new node.
    parent?.notifyListeners();
  }

  @override
  bool unlink() {
    // Add a null check to avoid unlink failure
    if (parent == null || list == null) {
      return false;
    }
    AppFlowyEditorLog.editor.debug('delete Node $this from path $path');
    super.unlink();
    // Clear the rank so a subsequent insert can regenerate a valid one;
    // otherwise the stale rank would fail RankedLinkedList's ordering check.
    rank = null;

    parent?._children.markAsDirty();
    _bumpPathGeneration();

    parent?.notifyListeners();
    parent = null;

    return true;
  }

  // reset the relationship of the node before inserting it to another node
  //  to ensure it is not in the tree
  // otherwise, it will throw a state error
  //  'Bad state: LinkedNode is already in a RankedLinkedList'
  void _resetRelationshipIfNeeded() {
    if (parent != null || list != null) {
      unlink();
    }
  }

  @override
  String toString() {
    return 'Node(id: $id, type: $type, attributes: $attributes, children: $children)';
  }

  Delta? get delta {
    if (attributes['delta'] is List) {
      return Delta.fromJson(attributes['delta']);
    }

    return null;
  }

  Map<String, Object> toJson({
    bool includeDatabaseIndex = true,
    bool includeId = true,
    bool includeRank = true,
  }) {
    final map = <String, Object>{
      if (includeId) 'id': id,
      if (includeDatabaseIndex) 'databaseIndex': databaseIndex,
      'type': type,
    };
    if (includeRank && rank != null) {
      map['rank'] = rank!;
    }
    if (children.isNotEmpty) {
      map['children'] = children
          .map(
            (node) => node.toJson(
              includeDatabaseIndex: includeDatabaseIndex,
              includeId: includeId,
              includeRank: includeRank,
            ),
          )
          .toList(growable: false);
    }
    if (_attributes.isNotEmpty) {
      // filter the null value; build a fresh map so we don't mutate the
      // unmodifiable view returned by `attributes`.
      final data = <String, Object>{};
      _attributes.forEach((key, value) {
        if (value != null) data[key] = value;
      });
      if (data.isNotEmpty) {
        map['data'] = data;
      }
    }

    return map;
  }

  /// Backwards-compatible serializer for downstream apps that wire a
  /// `databaseIndex` into their persistence layer. The editor itself never
  /// calls this; new code should use [toJson] instead.
  @Deprecated(
    'toJsonIndexed is kept only for downstream callers still relying on '
    'databaseIndex. New code should use toJson (which already serializes '
    'databaseIndex when includeDatabaseIndex is true).',
  )
  Map<String, Object> toJsonIndexed({double? index}) {
    final map = <String, Object>{
      'id': id,
      // ignore: deprecated_member_use_from_same_package
      'databaseIndex': index ?? databaseIndex,
      'type': type,
    };
    if (children.isNotEmpty) {
      map['children'] = children
          .map((node) => node.toJson())
          .toList(growable: false);
    }
    if (_attributes.isNotEmpty) {
      // Mirror toJson's null-filtering; can't `..removeWhere` the
      // unmodifiable view, so copy as we go.
      final data = <String, Object>{};
      _attributes.forEach((key, value) {
        if (value != null) data[key] = value;
      });
      if (data.isNotEmpty) {
        map['data'] = data;
      }
    }
    return map;
  }

  /// Copy the node
  ///
  /// If the parameters are not provided, the original value will be used.
  ///
  /// Be careful of the children, they will be deep copied if not provided.
  Node copyWith({
    String? type,
    Iterable<Node>? children,
    Attributes? attributes,
  }) {
    final node = Node(
      type: type ?? this.type,
      id: Uuid().v4(),
      attributes: attributes ?? {...this.attributes},
      children: children ?? [],
    );
    if (children == null && _children.isNotEmpty) {
      for (final child in _children) {
        node._children.add(child.copyWith()..parent = node);
      }
    }
    node.externalValues = externalValues;
    node.extraInfos = extraInfos;

    return node;
  }

  /// Deep copy the node
  ///
  /// This is a deep copy of the node, including the children.
  Node deepCopy() {
    return copyWith();
  }

  Path _computePath([Path previous = const []]) {
    final parent = this.parent;
    if (parent == null) {
      return previous;
    }
    final index = parent.children.indexOf(this);

    return parent._computePath([index, ...previous]);
  }

  /// check the integrity of the document (for DEBUG only)
  void checkDocumentIntegrity() {
    // skip the root node
    if (path.isNotEmpty) {
      // if node is rendered in the tree, its parent should not be null
      final errorMessage =
          '''Please submit an issue to https://github.com/AppFlowy-IO/appflowy-editor/issues if you see this error!
          node = ${toJson()}''';
      assert(parent != null, errorMessage);
      // also, its parent should contain this node
      assert(
        parent!.children.where((element) => element.id == id).length == 1,
        errorMessage,
      );
    }

    for (final child in children) {
      child.checkDocumentIntegrity();
    }
  }
}

extension NodeEquality on Iterable<Node> {
  bool equals(Iterable<Node> other) {
    if (length != other.length) {
      return false;
    }
    for (var i = 0; i < length; i++) {
      if (!_nodeEquals(elementAt(i), other.elementAt(i))) {
        return false;
      }
    }

    return true;
  }

  bool _nodeEquals<T, U>(T base, U other) =>
      identical(this, other) ||
      base is Node &&
          other is Node &&
          other.type == base.type &&
          other.children.equals(base.children);
}
